#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	xi="sudo xbps-install -S" \
	xr="sudo xbps-remove" \
	xq="xbps-query" \
	f="$FILE" \
	g="git" \
	ga="git add" \
	gs="git status" \
	gc="git commit" \
	gp="git push" \
	clone="git clone" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	ffmpeg="ffmpeg -hide_banner" \
	batt="acpi -bi" \
	wifi="sudo wpa_supplicant -B -Dnl80211,wext -c/etc/wpa_supplicant/wpa_supplicant.conf -iwls3" \
	#emacs='TERM=xterm-24bits emacsclient -nw -a=""' \
	emacs='emacsclient --create-frame -a=""' \
	rainbow="24-bit-color" \
	flex="clear && neofetch && fortune | cowthink && rainbow "

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
